import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthContext";
import NotesProvider from "../context/NoteContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NotesProvider>
            <ToastContainer hideProgressBar={true} autoClose={2500} />
            {children}
          </NotesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
